apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: "${email_address}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
    - dns01:
        azureDNS:
          clientID: "${client_id}"
          subscriptionID: "${subscription_id}"
          tenantID: "${tenant_id}"
          resourceGroupName: "${resource_group_name}"
          hostedZoneName: "${domain_name}"
          environment: AzurePublicCloud
          clientSecretSecretRef:
            name: azuredns-config
            key: client-secret
